src/Entity/CameraImg.php
<?php

namespace App\Entity;

use App\Repository\CameraImgRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CameraImgRepository::class)
 */
class CameraImg
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $datetime_img;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $filename;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDatetimeImg(): ?\DateTimeInterface
    {
        return $this->datetime_img;
    }

    public function setDatetimeImg(\DateTimeInterface $datetime_img): self
    {
        $this->datetime_img = $datetime_img;

        return $this;
    }

    public function getFilename(): ?string
    {
        return $this->filename;
    }

    public function setFilename(string $filename): self
    {
        $this->filename = $filename;

        return $this;
    }
}

src/Entity/RoverCmd.php
<?php

namespace App\Entity;

use App\Repository\RoverCmdRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=RoverCmdRepository::class)
 */
class RoverCmd
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $datetime_cmd;

    /**
     * @ORM\Column(type="integer")
     */
    private $ohm1;

    /**
     * @ORM\Column(type="integer")
     */
    private $ohm2;

    /**
     * @ORM\Column(type="integer")
     */
    private $ohm3;

    /**
     * @ORM\Column(type="integer")
     */
    private $ohm4;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDatetime(): ?\DateTimeInterface
    {
        return $this->datetime_cmd;
    }

    public function setDatetime(\DateTimeInterface $datetime_cmd): self
    {
        $this->datetime_cmd = $datetime_cmd;
        return $this;
    }

    public function getOhm1(): ?int
    {
        return $this->ohm1;
    }

    public function setOhm1(int $ohm1): self
    {
        $this->ohm1 = $ohm1;
        return $this;
    }

    public function getOhm2(): ?int
    {
        return $this->ohm2;
    }

    public function setOhm2(int $ohm2): self
    {
        $this->ohm2 = $ohm2;
        return $this;
    }

    public function getOhm3(): ?int
    {
        return $this->ohm3;
    }

    public function setOhm3(int $ohm3): self
    {
        $this->ohm3 = $ohm3;
        return $this;
    }

    public function getOhm4(): ?int
    {
        return $this->ohm4;
    }

    public function setOhm4(int $ohm4): self
    {
        $this->ohm4 = $ohm4;
        return $this;
    }
}

src/Controller/DefaultController.php
<?php
namespace App\Controller;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

use App\Entity\RoverCmd;
use App\Entity\CameraImg;

class DefaultController extends AbstractController
{
    /**
     * @Route("/")
     */
    public function index(): Response {
        $roverCmd = $this->getDoctrine()->getRepository(RoverCmd::class)->getLast();
        $cameraImg = $this->getDoctrine()->getRepository(CameraImg::class)->getLast();
        return $this->render('index.html.twig', array(
            'cameraImg' => $cameraImg,
            'roverCmd' => $roverCmd
        ));
    }

    /**
     * @Route("/registerRoverCmd")
     */
    public function registerRoverCmd(Request $request): Response {
        $data = json_decode($request->getContent());
        $roverCmd = new RoverCmd();
        $roverCmd->setDatetime( new \DateTime());
        $roverCmd->setOhm1($data->ohm1);
        $roverCmd->setOhm2($data->ohm2);
        $roverCmd->setOhm3($data->ohm3);
        $roverCmd->setOhm4($data->ohm4);

        $em = $this->getDoctrine()->getManager();
        $em->persist($roverCmd);
        $em->flush($roverCmd);
        
        return new Response();
    }

    /**
     * @Route("/registerRoverImg")
     */
    public function registerRoverImg(Request $request): Response {
        $file = $request->files->get('file');
        $img_time = new \DateTime();
        $filename = "rover-" . $img_time->format('YmdHis') . ".jpg";
        $file->move("imgs", $filename);

        $em = $this->getDoctrine()->getManager();
        $img = new CameraImg();
        $img->setDatetimeImg($img_time);
        $img->setFilename($filename);
        $em->persist($img);
        $em->flush();

        return new Response();
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>{% block title %}Welcome!{% endblock %}</title>
    {% block stylesheets %}{% endblock %}
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <link href="https://fonts.googleapis.com/css2?family=Black+Han+Sans&display=swap" rel="stylesheet">
  </head>
  <body>
    <nav class="navbar navbar-dark bg-dark">
      <a class="navbar-brand" href="/">
        <img src="logo.png" width="30" height="30" class="d-inline-block align-top" alt="" loading="lazy">
        <snap style="font-family: 'Black Han Sans', sans-serif;"> Midnight Blue</snap> | Turing Lab
      </a>
    </nav>
    {% block body %}{% endblock %}
    {% block javascripts %}{% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

templates/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
Midnight Blue | Turing Lab
{% endblock %}

{% block javascripts %}
<script>
  setTimeout(function(){
    window.location.reload(1);
  }, 5000);
</script>
{% endblock %}

{% block body %}
<div class="container">
  <div class="card" style="width: 640px; margin: 25px auto">
    {% if cameraImg %}
    <img src="imgs/{{cameraImg.filename}}" class="card-img-top" alt="..." height="480" width="640">
    <p style="font-size: small;">Imagen actualizada el {{cameraImg.datetimeImg.format('d/m/Y H:i:s') }}</p>
    {% else %}
    <p style="text-align: center; margin-top: 5px">No se ha recibido ninguna imagen</p>
    {% endif %}
    <div class="card-body" style="background-color: lightgray;">
      {% if roverCmd %}
      <p class="card-text"><b>Ohm1:</b> {{roverCmd.ohm1}}, <b>Ohm2:</b> {{roverCmd.ohm2}}, <b>Ohm3:</b> {{roverCmd.ohm3}}, <b>Ohm4:</b> {{roverCmd.ohm4}}</p>
      <p class="card-text" style="font-size: small;">Actualizado {{roverCmd.datetime.format('d/m/Y H:i:s') }}</p>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}